name: Trigger

on:
  workflow_dispatch:

env:
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}

jobs:
  check_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          cache: "pip"

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Check for updates
        id: check
        run: python scripts/ci.py check-update --github-output $GITHUB_OUTPUT -v

      - name: Create tag
        if: steps.check.outputs.need_update == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.check.outputs.new_tag }}
          draft: true
